import { describe, expect, it } from 'vitest';
import { ContentPackData, Target } from '../types';
import {
    applyGlobalScaleLabels,
    applySecondaryGroupingDisabled,
    applySecondaryGroupingEnabled,
    buildPackStructureLabels,
    collectPackOversizedWarnings,
    commitNumericScaleCsv,
    formatNumericScale,
    materializePackForSave,
    normalizePackIdentifiers,
    prepareBuilderPackForSave,
    reconcileScaleLabels,
    stripPackScoringScaleReferences,
    validateBuilderPackAuthoring,
    OVERSIZED_GROUP_EXTREME_THRESHOLD,
    OVERSIZED_GROUP_LARGE_THRESHOLD,
    OVERSIZED_WARNING_ADVICE,
    parseNumericScaleCsv,
    parseScaleLabelsCsv,
} from './assessmentPackAuthoring';
import { getStructureLabels, groupTargetsForDisplay } from './assessmentPackStructure';
import {
    appendTargetToDomain,
    createBuilderTarget,
    nextAutogeneratedTargetId,
} from './assessmentPackBuilder';

function makeTarget(overrides: Partial<Target> & Pick<Target, 'target_id'>): Target {
    const { scoring: scoringOverrides, ...rest } = overrides;
    return {
        title: overrides.target_id,
        success_criteria: '',
        materials: '',
        ...rest,
        scoring: {
            type: 'numeric',
            scale: [0, 1, 2, 3, 4],
            scale_labels: {},
            no_opportunity_allowed: false,
            ...scoringOverrides,
        },
    };
}

function makeFlatPack(): ContentPackData {
    return {
        pack_id: 'pack-1',
        org_id: 'org-1',
        title: 'Flat Pack',
        description: '',
        version: '1.0',
        domains: [
            {
                domain_id: 'DOM_1',
                title: 'Domain 1',
                targets: [
                    makeTarget({
                        target_id: 'T1',
                        scoring: {
                            type: 'numeric',
                            scale: [0, 1, 2, 3, 4],
                            scale_labels: {},
                            no_opportunity_allowed: false,
                        },
                    }),
                ],
            },
        ],
    };
}

describe('assessmentPackAuthoring', () => {
    it('parses numeric and label CSV fragments', () => {
        expect(parseNumericScaleCsv('0,1,2')).toEqual([0, 1, 2]);
        expect(parseScaleLabelsCsv('0:Not Yet|1:Emerging|2:Mastered')).toEqual({
            0: 'Not Yet',
            1: 'Emerging',
            2: 'Mastered',
        });
    });

    it('rejects malformed numeric scales instead of silently dropping tokens', () => {
        expect(() => parseNumericScaleCsv('0,a,1')).toThrow(/"a" is not a valid numeric score/);
        expect(() => parseNumericScaleCsv('0,,1')).toThrow(/empty values/i);
        expect(parseNumericScaleCsv('0,0.5,1')).toEqual([0, 0.5, 1]);
    });

    it('saves flat pack unchanged aside from materialized inline scoring', () => {
        const pack = makeFlatPack();
        const saved = materializePackForSave(pack);

        expect(saved.structure_labels).toBeUndefined();
        expect(saved.scoring_scales).toBeUndefined();
        expect(saved.domains[0].targets[0].scoring!.scale).toEqual([0, 1, 2, 3, 4]);
        expect(saved.domains[0].targets[0].scoring!.scale_id).toBeUndefined();
        expect(getStructureLabels(saved)).toEqual({
            primary_group: 'Domain',
            target: 'Target',
        });
    });

    it('enables structure labels when authors customize names', () => {
        const labels = buildPackStructureLabels('Level', 'Milestone', '', false);
        expect(labels).toEqual({
            primary_group: 'Level',
            target: 'Milestone',
        });
    });

    it('uses Secondary Group as the default secondary label when grouping is enabled', () => {
        const labels = buildPackStructureLabels('Primary Group', 'Target', '', true);
        expect(labels).toEqual({
            primary_group: 'Primary Group',
            secondary_group: 'Secondary Group',
            target: 'Target',
        });
    });

    it('enabling secondary grouping from Alpha defaults produces neutral three-level labels', () => {
        expect(
            applySecondaryGroupingEnabled({
                primaryGroup: 'Domain',
                secondaryGroup: '',
                target: 'Target',
            })
        ).toEqual({
            primaryGroup: 'Primary Group',
            secondaryGroup: 'Secondary Group',
            target: 'Target',
        });
    });

    it('enabling secondary grouping does not overwrite customized labels', () => {
        expect(
            applySecondaryGroupingEnabled({
                primaryGroup: 'Level',
                secondaryGroup: '',
                target: 'Target',
            })
        ).toEqual({
            primaryGroup: 'Level',
            secondaryGroup: 'Secondary Group',
            target: 'Target',
        });
    });

    it('disabling secondary grouping from neutral defaults reverts to Domain and Target', () => {
        expect(
            applySecondaryGroupingDisabled({
                primaryGroup: 'Primary Group',
                secondaryGroup: 'Secondary Group',
                target: 'Target',
            })
        ).toEqual({
            primaryGroup: 'Domain',
            secondaryGroup: '',
            target: 'Target',
        });
    });

    it('disabling secondary grouping does not overwrite a customized primary label', () => {
        expect(
            applySecondaryGroupingDisabled({
                primaryGroup: 'Module',
                secondaryGroup: 'Secondary Group',
                target: 'Target',
            })
        ).toEqual({
            primaryGroup: 'Module',
            secondaryGroup: '',
            target: 'Target',
        });
    });

    it('prepareBuilderPackForSave omits scoring_scales and strips scale_id references', () => {
        const pack = makeFlatPack();
        pack.scoring_scales = [
            {
                scale_id: 'scale-0-2',
                title: '0–2',
                type: 'numeric',
                scale: [0, 1, 2],
                scale_labels: { 0: 'Not yet', 1: 'Emerging', 2: 'Mastered' },
                no_opportunity_allowed: false,
            },
        ];
        pack.domains[0].targets[0].scoring = {
            type: 'numeric',
            scale_id: 'scale-0-2',
            scale: [0, 1, 2, 3, 4],
            scale_labels: {},
            no_opportunity_allowed: false,
        };

        const saved = prepareBuilderPackForSave(pack);

        expect(saved.scoring_scales).toBeUndefined();
        expect(saved.domains[0].targets[0].scoring!.scale_id).toBeUndefined();
        expect(saved.domains[0].targets[0].scoring!.scale).toEqual([0, 1, 2, 3, 4]);
    });

    it('stripPackScoringScaleReferences preserves inline per-target scoring', () => {
        const pack = makeFlatPack();
        pack.domains[0].targets[0].scoring = {
            type: 'numeric',
            scale: [0, 1, 2],
            scale_labels: { 0: 'Not Yet', 2: 'Mastered' },
            no_opportunity_allowed: true,
        };

        const stripped = stripPackScoringScaleReferences(pack);

        expect(stripped.scoring_scales).toBeUndefined();
        expect(stripped.domains[0].targets[0].scoring).toEqual({
            type: 'numeric',
            scale: [0, 1, 2],
            scale_labels: { 0: 'Not Yet', 2: 'Mastered' },
            no_opportunity_allowed: true,
        });
    });

    it('materializes referenced scale and preserves scale_id', () => {
        const pack = makeFlatPack();
        pack.scoring_scales = [
            {
                scale_id: 'scale-0-2',
                title: '0–2',
                type: 'numeric',
                scale: [0, 1, 2],
                scale_labels: { 0: 'Not yet', 1: 'Emerging', 2: 'Mastered' },
                no_opportunity_allowed: false,
            },
        ];
        pack.domains[0].targets[0].scoring = {
            type: 'numeric',
            scale_id: 'scale-0-2',
            scale_labels: {},
            no_opportunity_allowed: false,
        };

        const saved = materializePackForSave(pack);
        const scoring = saved.domains[0].targets[0].scoring!;

        expect(scoring.scale_id).toBe('scale-0-2');
        expect(scoring.scale).toEqual([0, 1, 2]);
        expect(scoring.scale_labels).toEqual({
            0: 'Not yet',
            1: 'Emerging',
            2: 'Mastered',
        });
    });

    it('lets target inline override win over referenced scale', () => {
        const pack = makeFlatPack();
        pack.scoring_scales = [
            {
                scale_id: 'scale-0-4',
                title: '0–4',
                type: 'numeric',
                scale: [0, 1, 2, 3, 4],
                scale_labels: { 0: 'Pack zero' },
                no_opportunity_allowed: false,
            },
        ];
        pack.domains[0].targets[0].scoring = {
            type: 'numeric',
            scale_id: 'scale-0-4',
            scale: [0, 1, 2],
            scale_labels: { 0: 'Target zero', 1: 'Target one', 2: 'Target two' },
            no_opportunity_allowed: true,
        };

        const saved = materializePackForSave(pack);
        expect(saved.domains[0].targets[0].scoring!.scale).toEqual([0, 1, 2]);
        expect(saved.domains[0].targets[0].scoring!.scale_labels![0]).toBe('Target zero');
        expect(saved.domains[0].targets[0].scoring!.no_opportunity_allowed).toBe(true);
    });

    it('strips secondary grouping when disabled at save', () => {
        const pack = makeFlatPack();
        pack.structure_labels = {
            primary_group: 'Domain',
            target: 'Target',
        };
        pack.domains[0].secondary_groups = [
            { secondary_group_id: 'sg-a', title: 'Group A' },
        ];
        pack.domains[0].targets[0].secondary_group_id = 'sg-a';

        const saved = materializePackForSave(pack);

        expect(saved.domains[0].secondary_groups).toBeUndefined();
        expect(saved.domains[0].targets[0].secondary_group_id).toBeUndefined();
    });

    it('preserves secondary grouping when enabled', () => {
        const pack = makeFlatPack();
        pack.structure_labels = {
            primary_group: 'Level',
            secondary_group: 'Domain',
            target: 'Milestone',
        };
        pack.domains[0].secondary_groups = [
            { secondary_group_id: 'sg-a', title: 'Group A' },
        ];
        pack.domains[0].targets[0].secondary_group_id = 'sg-a';

        const saved = materializePackForSave(pack);
        const sections = groupTargetsForDisplay(saved.domains[0]);

        expect(saved.domains[0].secondary_groups).toHaveLength(1);
        expect(saved.domains[0].targets[0].secondary_group_id).toBe('sg-a');
        expect(sections[0].targets).toHaveLength(1);
    });

    it('returns oversized warnings at threshold boundaries', () => {
        const targets = Array.from({ length: OVERSIZED_GROUP_LARGE_THRESHOLD }, (_, index) =>
            makeTarget({ target_id: `T${index + 1}` })
        );
        const pack: ContentPackData = {
            ...makeFlatPack(),
            domains: [{ domain_id: 'DOM_1', title: 'Big Domain', targets }],
        };

        const largeWarnings = collectPackOversizedWarnings(pack);
        expect(largeWarnings).toHaveLength(1);
        expect(largeWarnings[0].level).toBe('large');
        expect(largeWarnings[0].message).toBe(OVERSIZED_WARNING_ADVICE);

        const extremeTargets = Array.from(
            { length: OVERSIZED_GROUP_EXTREME_THRESHOLD },
            (_, index) => makeTarget({ target_id: `X${index + 1}` })
        );
        const extremePack: ContentPackData = {
            ...makeFlatPack(),
            domains: [{ domain_id: 'DOM_2', title: 'Huge Domain', targets: extremeTargets }],
        };
        const extremeWarnings = collectPackOversizedWarnings(extremePack);
        expect(extremeWarnings[0].level).toBe('extreme');
    });

    it('returns secondary-tier oversized warnings for large secondary groups', () => {
        const targets = Array.from({ length: OVERSIZED_GROUP_LARGE_THRESHOLD }, (_, index) =>
            makeTarget({
                target_id: `T${index + 1}`,
                secondary_group_id: 'sg-big',
            })
        );
        const pack: ContentPackData = {
            ...makeFlatPack(),
            structure_labels: {
                primary_group: 'Level',
                secondary_group: 'Domain',
                target: 'Milestone',
            },
            domains: [
                {
                    domain_id: 'DOM_1',
                    title: 'Level 1',
                    secondary_groups: [{ secondary_group_id: 'sg-big', title: 'Big Domain' }],
                    targets,
                },
            ],
        };

        const warnings = collectPackOversizedWarnings(pack);
        const secondaryWarnings = warnings.filter((warning) => warning.tier === 'secondary');

        expect(secondaryWarnings).toHaveLength(1);
        expect(secondaryWarnings[0].level).toBe('large');
        expect(secondaryWarnings[0].secondaryGroupId).toBe('sg-big');
        expect(secondaryWarnings[0].secondaryGroupTitle).toBe('Big Domain');
    });
});

describe('commitNumericScaleCsv', () => {
    it('accepts integer, decimal, negative, and whitespace-tolerant scales', () => {
        expect(commitNumericScaleCsv('0,1,2,3,4')).toEqual({
            ok: true,
            values: [0, 1, 2, 3, 4],
        });
        expect(commitNumericScaleCsv('0, 1, 2, 3, 4')).toEqual({
            ok: true,
            values: [0, 1, 2, 3, 4],
        });
        expect(commitNumericScaleCsv('0,0.5,1')).toEqual({ ok: true, values: [0, 0.5, 1] });
        expect(commitNumericScaleCsv('0,0.25,0.5,0.75,1')).toEqual({
            ok: true,
            values: [0, 0.25, 0.5, 0.75, 1],
        });
        expect(commitNumericScaleCsv('-1,0,1')).toEqual({ ok: true, values: [-1, 0, 1] });
    });

    it('rejects malformed completed scales with clinician-friendly messages', () => {
        expect(commitNumericScaleCsv('')).toEqual({
            ok: false,
            error: 'Enter numeric values separated by commas.',
        });
        expect(commitNumericScaleCsv('   ')).toEqual({
            ok: false,
            error: 'Enter numeric values separated by commas.',
        });
        expect(commitNumericScaleCsv('0,,1').ok).toBe(false);
        expect(commitNumericScaleCsv('0,a,1')).toEqual({
            ok: false,
            error: '"a" is not a valid numeric score.',
        });
        expect(commitNumericScaleCsv('0,NaN,1').ok).toBe(false);
        expect(commitNumericScaleCsv('0,Infinity,1').ok).toBe(false);
        expect(commitNumericScaleCsv('0.5.2,1').ok).toBe(false);
        expect(commitNumericScaleCsv(',,').ok).toBe(false);
        expect(commitNumericScaleCsv('0,1,0')).toEqual({
            ok: false,
            error: 'Score values must be unique.',
        });
        expect(commitNumericScaleCsv('0,1,').ok).toBe(false);
    });

    it('preserves order and decimals on successful commit formatting', () => {
        const result = commitNumericScaleCsv('0,0.5,1');
        expect(result.ok).toBe(true);
        if (result.ok) {
            expect(formatNumericScale(result.values)).toBe('0,0.5,1');
        }
    });
});

describe('numeric scale draft editing interactions', () => {
    it('allows intermediate commas and decimals to remain until commit', () => {
        let draft = '';
        let committed: number[] = [0, 1, 2, 3, 4];

        for (const chunk of ['0', ',', '1', ',', '2', ',', '3', ',', '4']) {
            draft += chunk;
            // Draft updates do not rewrite from number[]
            expect(draft.endsWith(chunk)).toBe(true);
            expect(committed).toEqual([0, 1, 2, 3, 4]);
        }
        expect(draft).toBe('0,1,2,3,4');

        draft = '0,';
        expect(commitNumericScaleCsv(draft).ok).toBe(false);
        expect(draft).toBe('0,');

        draft = '0,1,';
        expect(draft).toBe('0,1,');
        expect(commitNumericScaleCsv(draft).ok).toBe(false);

        draft = '0.';
        expect(draft).toBe('0.');
        expect(commitNumericScaleCsv(draft).ok).toBe(false);

        draft = '0.5';
        const half = commitNumericScaleCsv(draft);
        expect(half).toEqual({ ok: true, values: [0.5] });
        if (half.ok) {
            committed = half.values;
        }

        draft = '0,0.5,1';
        const decimalScale = commitNumericScaleCsv(draft);
        expect(decimalScale).toEqual({ ok: true, values: [0, 0.5, 1] });
    });
});

describe('scale label reconciliation', () => {
    it('preserves labels for unchanged scores and drops stale mappings', () => {
        expect(
            reconcileScaleLabels([0, 0.5, 1], {
                0: 'None',
                1: 'Full',
                2: 'Stale',
            })
        ).toEqual({
            0: 'None',
            1: 'Full',
        });
    });
});

describe('builder identifier validation', () => {
    it('rejects empty and duplicate domain IDs after trim', () => {
        const pack: ContentPackData = {
            ...makeFlatPack(),
            title: 'Pack',
            domains: [
                { domain_id: '  ', title: 'A', targets: [] },
                { domain_id: 'A', title: 'B', targets: [] },
                { domain_id: ' A ', title: 'C', targets: [] },
            ],
        };

        const issues = validateBuilderPackAuthoring(pack);
        expect(issues.some((issue) => issue.message.includes('Enter a domain ID'))).toBe(true);
        expect(issues.some((issue) => issue.message.includes('already used'))).toBe(true);
    });

    it('rejects empty and pack-global duplicate target IDs', () => {
        const pack: ContentPackData = {
            ...makeFlatPack(),
            title: 'Pack',
            domains: [
                {
                    domain_id: 'A',
                    title: 'Domain A',
                    targets: [
                        makeTarget({ target_id: 'T1' }),
                        makeTarget({ target_id: '  ' }),
                    ],
                },
                {
                    domain_id: 'B',
                    title: 'Domain B',
                    targets: [makeTarget({ target_id: 'T1' })],
                },
            ],
        };

        const issues = validateBuilderPackAuthoring(pack);
        expect(issues.some((issue) => issue.message.includes('Enter a target ID'))).toBe(true);
        expect(
            issues.some((issue) =>
                issue.message.includes('unique across the assessment')
            )
        ).toBe(true);
    });

    it('Uniform mode requires only a complete default_scoring, not per-target scales', () => {
        const pack: ContentPackData = {
            ...makeFlatPack(),
            title: 'Uniform Pack',
            scoring_mode: 'uniform',
            default_scoring: {
                type: 'numeric',
                scale: [0, 1, 2, 3, 4],
                scale_labels: {},
                no_opportunity_allowed: true,
            },
            domains: [
                {
                    domain_id: 'A',
                    title: 'Domain A',
                    targets: [
                        {
                            target_id: 'A1',
                            title: 'A1',
                            success_criteria: '',
                            materials: '',
                        },
                    ],
                },
            ],
        };

        expect(validateBuilderPackAuthoring(pack)).toEqual([]);
    });

    it('Custom Inherited targets do not require per-target scales; Overrides do', () => {
        const pack: ContentPackData = {
            ...makeFlatPack(),
            title: 'Custom Pack',
            scoring_mode: 'custom',
            default_scoring: {
                type: 'numeric',
                scale: [0, 1, 2, 3, 4],
                scale_labels: {},
                no_opportunity_allowed: true,
            },
            domains: [
                {
                    domain_id: 'A',
                    title: 'Domain A',
                    targets: [
                        {
                            target_id: 'A1',
                            title: 'Inherited',
                            success_criteria: '',
                            materials: '',
                        },
                        {
                            target_id: 'A2',
                            title: 'Broken override',
                            success_criteria: '',
                            materials: '',
                            scoring: {
                                type: 'numeric',
                                scale_labels: {},
                                no_opportunity_allowed: false,
                            },
                        },
                    ],
                },
            ],
        };

        const issues = validateBuilderPackAuthoring(pack);
        expect(issues.some((issue) => issue.targetIndex === 0)).toBe(false);
        expect(
            issues.some(
                (issue) =>
                    issue.targetIndex === 1 &&
                    issue.message.includes('Enter numeric values separated by commas')
            )
        ).toBe(true);
    });

    it('normalizes identifier whitespace on save preparation', () => {
        const pack = makeFlatPack();
        pack.domains[0].domain_id = ' A ';
        pack.domains[0].targets[0].target_id = ' T1 ';

        const saved = prepareBuilderPackForSave(pack);
        expect(saved.domains[0].domain_id).toBe('A');
        expect(saved.domains[0].targets[0].target_id).toBe('T1');
    });

    it('nextAutogeneratedTargetId skips collisions including pack-reserved IDs', () => {
        const domain = {
            domain_id: 'A',
            title: 'Domain A',
            targets: [makeTarget({ target_id: 'A1' }), makeTarget({ target_id: 'A2' })],
        };
        // Simulate delete A1 then add: length+1 would be A3, but also reserve A3 from another domain
        domain.targets = [makeTarget({ target_id: 'A2' })];
        expect(nextAutogeneratedTargetId(domain)).toBe('A1');
        expect(nextAutogeneratedTargetId(domain, ['A1'])).toBe('A3');
        expect(createBuilderTarget(domain, [0, 1], undefined, ['A1', 'A3']).target_id).toBe('A4');
    });
});

describe('global vs target-specific scale behaviour', () => {
    it('applyGlobalScaleLabels overwrites labels only, not target scales', () => {
        const domains = [
            {
                domain_id: 'A',
                title: 'A',
                targets: [
                    makeTarget({
                        target_id: 'A1',
                        scoring: {
                            type: 'numeric',
                            scale: [0, 0.5, 1],
                            scale_labels: { 0: 'Local' },
                            no_opportunity_allowed: true,
                        },
                    }),
                ],
            },
        ];

        const next = applyGlobalScaleLabels(domains, {
            0: 'Global zero',
            0.5: 'Global half',
            1: 'Global one',
        });

        expect(next[0].targets[0].scoring!.scale).toEqual([0, 0.5, 1]);
        expect(next[0].targets[0].scoring!.scale_labels).toEqual({
            0: 'Global zero',
            0.5: 'Global half',
            1: 'Global one',
        });
    });

    it('new targets snapshot default scale; later default changes do not rewrite existing scales', () => {
        let domain = {
            domain_id: 'A',
            title: 'A',
            targets: [] as Target[],
        };
        domain = appendTargetToDomain(domain, [0, 1, 2, 3, 4]);
        expect(domain.targets[0].scoring!.scale).toEqual([0, 1, 2, 3, 4]);

        domain = appendTargetToDomain(domain, [0, 0.5, 1], undefined, [
            domain.targets[0].target_id,
        ]);
        expect(domain.targets[0].scoring!.scale).toEqual([0, 1, 2, 3, 4]);
        expect(domain.targets[1].scoring!.scale).toEqual([0, 0.5, 1]);
    });

    it('target-specific decimal scales round-trip through prepareBuilderPackForSave', () => {
        const pack = makeFlatPack();
        pack.domains[0].targets[0].scoring = {
            type: 'numeric',
            scale: [0, 0.5, 1],
            scale_labels: { 0: 'None', 0.5: 'Partial', 1: 'Full' },
            no_opportunity_allowed: true,
        };

        const saved = prepareBuilderPackForSave(pack);
        expect(saved.domains[0].targets[0].scoring!.scale).toEqual([0, 0.5, 1]);
        expect(saved.domains[0].targets[0].scoring!.scale_labels).toEqual({
            0: 'None',
            0.5: 'Partial',
            1: 'Full',
        });

        const reloadedDraft = formatNumericScale(
            saved.domains[0].targets[0].scoring!.scale ?? []
        );
        expect(reloadedDraft).toBe('0,0.5,1');
        expect(commitNumericScaleCsv(reloadedDraft)).toEqual({
            ok: true,
            values: [0, 0.5, 1],
        });
    });

    it('normalizePackIdentifiers is available for explicit trim without mutating input', () => {
        const pack = makeFlatPack();
        pack.domains[0].domain_id = ' Z ';
        const normalized = normalizePackIdentifiers(pack);
        expect(pack.domains[0].domain_id).toBe(' Z ');
        expect(normalized.domains[0].domain_id).toBe('Z');
    });
});
