import { Domain, Target } from '../types';

export interface TargetIndexEntry {
    target: Target;
    index: number;
}

function defaultTargetScoring(scale: number[]): Target['scoring'] {
    return {
        type: 'numeric',
        scale,
        scale_labels: {},
        no_opportunity_allowed: true,
    };
}

/**
 * Next autogenerated target_id for Builder: `${domain_id}${n}`.
 * Skips IDs already present on this domain or in reservedTargetIds (pack-global).
 */
export function nextAutogeneratedTargetId(
    domain: Domain,
    reservedTargetIds: Iterable<string> = []
): string {
    const taken = new Set<string>();
    for (const id of reservedTargetIds) {
        const trimmed = id.trim();
        if (trimmed) {
            taken.add(trimmed);
        }
    }
    for (const target of domain.targets) {
        const trimmed = target.target_id.trim();
        if (trimmed) {
            taken.add(trimmed);
        }
    }

    const prefix = domain.domain_id.trim();
    let n = 1;
    let candidate = `${prefix}${n}`;
    while (taken.has(candidate)) {
        n += 1;
        candidate = `${prefix}${n}`;
    }
    return candidate;
}

/** Creates a new target for Builder authoring without mutating the domain. */
export function createBuilderTarget(
    domain: Domain,
    defaultScale: number[],
    secondaryGroupId?: string,
    reservedTargetIds: Iterable<string> = []
): Target {
    return {
        target_id: nextAutogeneratedTargetId(domain, reservedTargetIds),
        title: '',
        description: '',
        success_criteria: '',
        materials: '',
        examples: '',
        instructions: '',
        notes: '',
        scoring: defaultTargetScoring(defaultScale),
        ...(secondaryGroupId ? { secondary_group_id: secondaryGroupId } : {}),
    };
}

/** Appends a target to domain.targets[]; optional secondary_group_id for grouped authoring. */
export function appendTargetToDomain(
    domain: Domain,
    defaultScale: number[],
    secondaryGroupId?: string,
    reservedTargetIds: Iterable<string> = []
): Domain {
    return {
        ...domain,
        targets: [
            ...domain.targets,
            createBuilderTarget(domain, defaultScale, secondaryGroupId, reservedTargetIds),
        ],
    };
}

/** Updates only target.secondary_group_id for a target at the given flat index. */
export function moveTargetSecondaryGroup(
    domain: Domain,
    targetIndex: number,
    secondaryGroupId: string | undefined
): Domain {
    const targets = domain.targets.map((target, index) => {
        if (index !== targetIndex) {
            return target;
        }

        if (!secondaryGroupId?.trim()) {
            const { secondary_group_id: _removed, ...rest } = target;
            return rest;
        }

        return { ...target, secondary_group_id: secondaryGroupId };
    });

    return { ...domain, targets };
}

/** Non-mutating view of targets belonging to a secondary group. */
export function getTargetsForSecondaryGroup(
    domain: Domain,
    secondaryGroupId: string
): TargetIndexEntry[] {
    return domain.targets
        .map((target, index) => ({ target, index }))
        .filter(({ target }) => target.secondary_group_id === secondaryGroupId);
}

/** Non-mutating view of targets without secondary_group_id. */
export function getUngroupedTargetEntries(domain: Domain): TargetIndexEntry[] {
    return domain.targets
        .map((target, index) => ({ target, index }))
        .filter(({ target }) => !target.secondary_group_id?.trim());
}
